export default [
  {
    id: "0",
    title: " Repository",
    description: "Naruto Uzumaki",
    link: "The many lives lost during long years of conflict... because of those selfless sacrifices, we are able to bathe in peace and prosperity now. To ingrain this history within the new generation will be a vital cog in helping to maintain the peace.",
  },
  {
    id: "1",
    title: "GitHub",
    description: "Naruto Uzumaki",
    link: "There is no telling what kind of pain will come  after me, but... if I stop believing because of that, if the hero should change, it'll turn into another story from the one my master left behind. Then it wont be Naruto! I can't write novels like my master did. That's why the sequel has to come from the life I live no matter how great the pain, I'll continue walking because that's who Naruto is!",
  },
  {
    id: "2",
    title: "Open source",
    description: "Naruto Uzumaki",
    link: "Because they saved me from myself, they rescued me from my loneliness. They were the first to accept me for who I am. They're my friends.",
  },
  {
    id: "3",
    title: "Pull request",
    description: "Naruto Uzumaki",
    link: "ce you question your own belief, it's over.",
  },
  {
    id: "4",
    title: "Commit",
    description: "Naruto Uzumaki",
    link: "Don't underestimate me! I don't quit and I don't run! You can act tough all you want! You're not gonna scare me off! No way! I don't care if I DO get stuck as a Genin for the rest of my life! I'll still be Hokage someday!",
  },
  {
    id: "5",
    title: "FOSS",
    description: "Naruto Uzumaki",
    link: "People who continue to put their lives on the line to defend their faith become heroes and continue to exist on in legend.",
  },
  {
    id: "6",
    title: "Fork",
    description: "Naruto Uzumaki",
    link: "en you give up, your dreams and everything else, they're gone.",
  },
  {
    id: "7",
    title: "Issues",
    description: "Naruto Uzumaki",
    link: "Hard work is worthless for those that don't believe in themselves.",
  },
  {
    id: "8",
    title: "Clone",
    description: "Naruto Uzumaki",
    link: "If you don't like the hand that fate's dealt you with, fight for a new one!",
  },
  {
    id: "9",
    title: "License",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "10",
    title: "Community",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "11",
    title: "Contributor",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "12",
    title: "Git",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "13",
    title: "OSI",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "14",
    title: "Source Code",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "15",
    title: "Copy-Left License",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "16",
    title: "Permissive License",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "17",
    title: "README",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "18",
    title: "Maintainers",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "19",
    title: "Good-first-issue",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
  {
    id: "20",
    title: "Contributing Guideline",
    description: "Naruto Uzumaki",
    link: "The pain of being alone is completely out of this world, isn't it? I don't know why, but I understand your feelings so much, it actually hurts.",
  },
];
