import Head from 'next/head'
import Navbar from '../Components/Navbar'
import Words from '../Components/Words'
import Welcome from '../Components/Welcome'


export default function Home() {
  console.log(Words)
  return (
    <>
      <Head>
        <title>Open Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className=''>
<Welcome/>
      </main>
    </>
  );
}
